// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbas_waV63ybKo7b6GuxBetQczj91w3Fg',
    appId: '1:375429456766:web:581d410a729ad6697c892f',
    messagingSenderId: '375429456766',
    projectId: 'fir-ff9c3',
    authDomain: 'fir-ff9c3.firebaseapp.com',
    storageBucket: 'fir-ff9c3.firebasestorage.app',
    measurementId: 'G-QT203D6KPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEEIzVsb2DGxBbJkR_Ofd8GtIk9AxxUtg',
    appId: '1:375429456766:android:a2b621d7adbb46bc7c892f',
    messagingSenderId: '375429456766',
    projectId: 'fir-ff9c3',
    storageBucket: 'fir-ff9c3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbas_waV63ybKo7b6GuxBetQczj91w3Fg',
    appId: '1:375429456766:web:3a64b2ff6b72288c7c892f',
    messagingSenderId: '375429456766',
    projectId: 'fir-ff9c3',
    authDomain: 'fir-ff9c3.firebaseapp.com',
    storageBucket: 'fir-ff9c3.firebasestorage.app',
    measurementId: 'G-KQTEN0HJS1',
  );
}
